
dynamic EnglishStrings = {
  "login" : "Login",
  "doNotHaveAccount" : "Don't have an Account?",
  "register" : "Register",
  "email" : "Email",
  "emailEmptyError" : "The Email can't be empty",
  "password" : "Password",
  "passwordEmptyError" : "The Password can't be empty",
  "passwordLengthError" : "The Password length should be [8 - 16] letters",
  "error" : "Error",
  "createAccount" : "Create new Account",
  "alreadyRegistered" : "Already Registered?",
  "name" : "Name",
  "fullName" : "Full Name",
  "nameEmptyError" : "The Name can't be empty",
  "person" : "Person",
  "company" : "Company",
  "settings" : "Settings",
  "language" : "Language",
  "arabic" : "Arabic",
  "english" : "English",
  "searchHintText" : "Search jobs...",
  "explore" : "Explore",
  "saved" : "Saved",
  "save" : "Save",
  "selectYourLanguage" : "Select your Language",
  "letsStart" : "Let's start",
  "onboardingTitle1" : "Explore Jobs",
  "onboardingBody1" : "Explore many jobs in different fields",
  "onboardingTitle2" : "Apply to the Job",
  "onboardingBody2" : "Find the job that match your skills and contact with the companies",
  "onboardingTitle3" : "Job offer",
  "onboardingBody3" : "The companies will contact you for a job opportunity",
  "skip" : "SKIP",
  "gender" : "Gender",
  "male" : "Male",
  "female" : "Female",
  "age" : "Age",
  "educationLevel" : "Education Level",
  "bachelors" : "Bachelors",
  "masters" : "Masters",
  "doctoral" : "Doctoral",
  "accountType" : "Account Type",
  "ageEmptyError" : "Age should not be empty",
  "ageParseError" : "Age should be an Integer",
  "location" : "Location",
  "locationEmptyError" : "Location should not be empty",
  "phoneNumber" : "Phone Number",
  "phoneNumberEmptyError" : "Phone Number should not be empty",
  "myJobs" : "My Jobs",
  "jobs" : "Jobs",
  "archived" : "Archived",
  "description" : "Description",
  "requirements" : "Requirements",
  "benefits" : "Benefits",
  "salary" : "Salary",
  "deadline" : "Deadline",
  "contactInfo" : "Contact Info",
  "chooseOption" : "Choose an Option",
  "camera" : "Camera",
  "gallery" : "Gallery",
  "fieldMissing" : "This Field is missing",
  "registerNameHint" : "Full name / Company name",
  "enterValidEmail" : "Enter a valid Email address",
  "enterValidPassword" : "Enter a valid password",
  "enterValidPhone" : "Enter a valid phone number",
  "enterValidAddress" : "Enter a valid address",
  "address" : "Address",
  "fillAllFieldsError" : "Please fill all fields",
  "jobCategory" : "Job Category",
  "jobTitle" : "Job Title",
  "jobDescription" : "Job Description",
  "jobDeadline" : "Job Deadline Date",
  "post" : "Post",
  "close" : "Close",
  "cancelFilter" : "Cancel Filter",
  "averageAge" : "Average Age",
  "sendCV" : "Send your CV",
  "applyNow" : "Apply Now",
  "uploadedOn" : "Uploaded on",
  "clientLogin" : "Login as Client",
  "companyLogin" : "Login as Company",
  "clientRegister" : "Register as Client",
  "companyRegister" : "Register as Company",
  "emailValidationError" : "please enter a valid Email address",
  "birthDate" : "Birth Date",
  "chooseGender" : "Choose Gender",
  "other" : "Other",
  "companyNameHint" : "Company Name",
  "addressValidationError" : "please enter a valid address",
  "jobSearch" : "Search for Job",
  "search" : "Search",
  "applyLink" : "Apply Link",
  "registeredSuccessful" : "Registered Successfully",
  "phoneValidError" : "Phone number is not valid",
  "loggedSuccessful" : "Logged in successfully",
  "selectGender" : "Select your Gender",
  "signOut" : "Sign Out",
  "signOutConfirmMessage" : "Do you want to Log out?",
  "no" : "No",
  "yes" : "Yes",
  "invalidLoginData" : "Invalid username or password",
  "unknownError" : "Something wrong happened",
  "from" : "From",
  "to" : "To",
  "ageInvalid" : "Invalid Age",
  "jobPublished" : "Job has been published",
  "applyLinkWarning" : "Make sure to put \"https://\" in the start of the link",
  "jobDeleted" : "Job has been deleted successfully",
  "jobUpdated" : "Job has been updated successfully",
  "editJobData" : "Edit Job Data",


  "deleteJob" : "Delete Job",
  "deleteJobConfirmMessage" : "Do you want to delete this job ?",

};

dynamic ArabicStrings = {
  "login" : "تسجيل الدخول",
  "doNotHaveAccount" : "ليس لديك حساب؟",
  "register" : "تسجيل الحساب",
  "email" : "البريد الإلكتروني",
  "emailEmptyError" : "البريد الإلكتروني لا يجب أن يكون فارغ",
  "password" : "كلمة المرور",
  "passwordEmptyError" : "كلمة المرور لا يجب ان تكون فارغه",
  "passwordLengthError" : "يجب أن يكون عدد أحرف كلمة المرور من بين [8 - 16]",
  "error" : "خطأ",
  "createAccount" : "عمل حساب جديد",
  "alreadyRegistered" : "لديك حساب بالفعل؟",
  "name" : "الإسم",
  "fullName" : "الاسم بالكامل",
  "nameEmptyError" : "لا يجب أن يكون الإسم فارغ",
  "person" : "شخص",
  "company" : "شركة",
  "settings" : "الإعدادات",
  "language" : "اللغة",
  "arabic" : "العربية",
  "english" : "الانجليزية",
  "searchHintText" : "بحث عن وظائف...",
  "explore" : "تصفح",
  "saved" : "محفوظات",
  "save" : "حفظ",
  "selectYourLanguage" : "إختار لغتك",
  "letsStart" : "لنبدأ",
  "onboardingTitle1" : "تصفح الوظائف",
  "onboardingBody1" : "تصفح العديد من الوظائف في مختلف المجالات",
  "onboardingTitle2" : "تقديم على الوظيفة",
  "onboardingBody2" : "اعثر على الوظيفة اللتي تناسب مهاراتك و تواصل مع الشركات",
  "onboardingTitle3" : "عرض العمل",
  "onboardingBody3" : "سوف تتواصل معك الشركات من اجل فرص العمل",
  "skip" : "تخطي",
  "gender" : "الجنس",
  "male" : "ذكر",
  "female" : "أنثى",
  "age" : "السن",
  "educationLevel" : "المرحلة التعليمية",
  "bachelors" : "البكالوريوس",
  "masters" : "الماجستير",
  "doctoral" : "الدكتوراه",
  "accountType" : "نوع الحساب",
  "ageEmptyError" : "لا يجب أن يكون العمر فارغا",
  "ageParseError" : "يجب أن يكون العمر عددًا صحيحًا",
  "location" : "الموقع",
  "locationEmptyError" : "لا يجب ان يكون الموقع فارغا",
  "phoneNumber" : "رقم التليفون",
  "phoneNumberEmptyError" : "لا يجب ان يكون رقم الهاتف فارغا",
  "myJobs" : "وظائفي",
  "jobs" : "وظائف",
  "archived" : "أرشيف",
  "description" : "الوصف",
  "requirements" : "المتطلبات",
  "benefits" : "الفوائد",
  "salary" : "الراتب",
  "deadline" : "اخر موعد للتقديم",
  "contactInfo" : "معلومات التواصل",
  "chooseOption" : "اختر خيار",
  "camera" : "كاميرا",
  "gallery" : "المعرض",
  "fieldMissing" : "المكان مفقود",
  "registerNameHint" : "الاسم كامل / اسم الشركه",
  "enterValidEmail" : "ادخل بريد الكتروني صالح",
  "enterValidPassword" : "ادخل كلمه مرور صالحه",
  "enterValidPhone" : "ادخل رقم محمول صالح",
  "enterValidAddress" : "ادخل عنوان صالح",
  "address" : "عنوان",
  "fillAllFieldsError" : "من فضلك ادخل جميع البيانات",
  "jobCategory" : "فئة الوظيفة",
  "jobTitle" : "مسمى الوظيفة",
  "jobDescription" : "وصف للوظيفه",
  "jobDeadline" : "اخر موعد للتقديم",
  "post" : "نشر",
  "close" : "اغلاق",
  "cancelFilter" : "الغاء التصفيه",
  "averageAge" : "متوسط الأعمار",
  "sendCV" : "ارسل سيرتك الذاتية",
  "applyNow" : "سجل الان",
  "uploadedOn" : "تاريخ النشر",
  "clientLogin" : "تسجيل دخول ك عميل",
  "companyLogin" : "تسجيل دخول ك شركة",
  "clientRegister" : "تسجيل حساب ك عميل",
  "companyRegister" : "تسجيل حساب ك شركة",
  "emailValidationError" : "ادخل بريد الكتروني صحيح",
  "birthDate" : "تاريخ الميلاد",
  "chooseGender" : "اختار الجنس",
  "other" : "اخرى",
  "companyNameHint" : "اسم الشركة",
  "addressValidationError" : "ادخل عنوان صحيح",
  "jobSearch" : "البحث عن وظيفة",
  "search" : "ابحث",
  "applyLink" : "رابط التسجيل",
  "registeredSuccessful" : "تم تسجيل الحساب بنجاح",
  "phoneValidError" : "رقم الهاتف غير صحيح",
  "loggedSuccessful" : "تم تسجيل دخول بنجاح",
  "selectGender" : "اختار الجنس",
  "signOut" : "تسجيل الخروج",
  "signOutConfirmMessage" : "هل تريد تسجيل الخروج ؟",
  "no" : "لا",
  "yes" : "نعم",
  "invalidLoginData" : "البريد الالكتروني او كلمة السر غير صحيحة",
  "unknownError" : "حدث شيء خطأ",
  "from" : "من",
  "to" : "الى",
  "ageInvalid" : "عُمر غير صحيح",
  "jobPublished" : "تم نشر الوظيفة",
  "applyLinkWarning" : "تأكد من وجود \"https://\" في بداية رابط التسجيل",
  "jobDeleted" : "تم حذف الوظيفة بنجاح",
  "jobUpdated" : "تم تعديل الوظيفة بنجاح",
  "editJobData" : "تعديل بيانات الوظيفة",

  "deleteJob" : "حذف الوظيفة",
  "deleteJobConfirmMessage" : "هل تريد حذف هذه الوظيفة ؟",

};
