
dynamic EnglishStrings = {
  "login" : "Login",
  "doNotHaveAccount" : "Don't have an Account?",
  "register" : "Register",
  "email" : "Email",
  "emailEmptyError" : "The Email can't be empty",
  "password" : "Password",
  "passwordEmptyError" : "The Password can't be empty",
  "passwordLengthError" : "The Password length should be [8 - 16] letters",
  "error" : "Error",
  "createAccount" : "Create new Account",
  "alreadyRegistered" : "Already Registered?",
  "name" : "Name",
  "nameEmptyError" : "The Name can't be empty",
  "person" : "Person",
  "company" : "Company",
  "settings" : "Settings",
  "language" : "Language",
  "arabic" : "Arabic",
  "english" : "English",
  "searchHintText" : "Search jobs, company...",
  "explore" : "Explore",
  "saved" : "Saved",
  "save" : "Save",
  "selectYourLanguage" : "Select your Language",
  "letsStart" : "Let's start",
  "onboardingTitle1" : "Explore Jobs",
  "onboardingBody1" : "Explore many jobs in different fields",
  "onboardingTitle2" : "Apply to the Job",
  "onboardingBody2" : "Find the job that match your skills and contact with the companies",
  "onboardingTitle3" : "Job offer",
  "onboardingBody3" : "The companies will contact you for a job opportunity",
  "skip" : "SKIP",
  "gender" : "Gender",
  "male" : "Male",
  "female" : "Female",
  "age" : "Age",
  "educationLevel" : "Education Level",
  "bachelors" : "Bachelors",
  "masters" : "Masters",
  "doctoral" : "Doctoral",
  "accountType" : "Account Type",
  "ageEmptyError" : "Age should not be empty",
  "ageParseError" : "Age should be an Integer",
  "location" : "Location",
  "locationEmptyError" : "Location should not be empty",
  "phoneNumber" : "Phone Number",
  "phoneNumberEmptyError" : "Phone Number should not be empty",

  "myJobs" : "My Jobs",
  "archived" : "Archived",

  "description" : "Description",
  "requirements" : "Requirements",
  "benefits" : "Benefits",
  "salary" : "Salary",
  "deadline" : "Deadline",
  "contactInfo" : "Contact Info",

};

dynamic ArabicStrings = {
  "login" : "تسجيل الدخول",
  "doNotHaveAccount" : "ليس لديك حساب؟",
  "register" : "تسجيل",
  "email" : "البريد الإلكتروني",
  "emailEmptyError" : "البريد الإلكتروني لا يجب أن يكون فارغ",
  "password" : "كلمة المرور",
  "passwordEmptyError" : "كلمة المرور لا يجب ان تكون فارغه",
  "passwordLengthError" : "يجب أن يكون عدد أحرف كلمة المرور من بين [8 - 16]",
  "error" : "خطأ",
  "createAccount" : "عمل حساب جديد",
  "alreadyRegistered" : "لديك حساب بالفعل؟",
  "name" : "الإسم",
  "nameEmptyError" : "لا يجب أن يكون الإسم فارغ",
  "person" : "شخص",
  "company" : "شركة",
  "settings" : "الإعدادات",
  "language" : "اللغة",
  "arabic" : "العربية",
  "english" : "الانجليزية",
  "searchHintText" : "بحث عن وظائف, شركات...",
  "explore" : "تصفح",
  "saved" : "محفوظات",
  "save" : "حفظ",
  "selectYourLanguage" : "إختار لغتك",
  "letsStart" : "لنبدأ",
  "onboardingTitle1" : "تصفح الوظائف",
  "onboardingBody1" : "تصفح العديد من الوظائف في مختلف المجالات",
  "onboardingTitle2" : "تقديم على الوظيفة",
  "onboardingBody2" : "اعثر على الوظيفة اللتي تناسب مهاراتك و تواصل مع الشركات",
  "onboardingTitle3" : "عرض العمل",
  "onboardingBody3" : "سوف تتواصل معك الشركات من اجل فرص العمل",
  "skip" : "تخطي",
  "gender" : "الجنس",
  "male" : "ذكر",
  "female" : "أنثى",
  "age" : "السن",
  "educationLevel" : "المرحلة التعليمية",
  "bachelors" : "البكالوريوس",
  "masters" : "الماجستير",
  "doctoral" : "الدكتوراه",
  "accountType" : "نوع الحساب",
  "ageEmptyError" : "لا يجب أن يكون العمر فارغا",
  "ageParseError" : "يجب أن يكون العمر عددًا صحيحًا",
  "location" : "الموقع",
  "locationEmptyError" : "لا يجب ان يكون الموقع فارغا",
  "phoneNumber" : "رقم التليفون",
  "phoneNumberEmptyError" : "لا يجب ان يكون رقم الهاتف فارغا",

  "myJobs" : "وظائفي",
  "archived" : "أرشيف",

  "description" : "الوصف",
  "requirements" : "المتطلبات",
  "benefits" : "الفوائد",
  "salary" : "الراتب",
  "deadline" : "اخر موعد للتقديم",
  "contactInfo" : "معلومات التواصل",
};